version: '3'
services:
  comgongBOT-admin:
    build: .
    container_name: admin-container
    image: admin-image
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    restart: always
    ports:
      - 8080:8080