version: '3'
services:
  vuedmin:
    build: .
    container_name: vue-container
    image: vue-image
    volumes:
      - .:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    restart: always
    ports:
      - 8080:8080